## demo2: Extract data from NetCDF file profiles and convert to CSV

This demo illustrates how to:

1. Load the global Argo profile index.
2. Define a geographic polygon (e.g., zone off Baja California Sur, Mexico).
3. Apply a vectorized point-in-polygon filter.
4. Extract vertical profile data from the selected NetCDF files.

In [1]:
import pandas as pd
import cluster_qc

In [2]:
# directory = pd.read_csv('ftp://ftp.ifremer.fr/ifremer/argo/ar_index_global_prof.txt', skiprows=8).dropna()
directory = pd.read_csv('C:/bd/argo/202406-ArgoData/dac/ar_index_global_prof.txt', skiprows=8).dropna()
directory

,file,date,latitude,longitude,ocean,profiler_type,institution,date_update
0,aoml/13857/profiles/R13857_001.nc,1.997073e+13,0.267,-16.032,A,845,AO,20181011180520
1,aoml/13857/profiles/R13857_002.nc,1.997081e+13,0.072,-17.659,A,845,AO,20181011180521
2,aoml/13857/profiles/R13857_003.nc,1.997082e+13,0.543,-19.622,A,845,AO,20181011180521
3,aoml/13857/profiles/R13857_004.nc,1.997083e+13,1.256,-20.521,A,845,AO,20181011180521
4,aoml/13857/profiles/R13857_005.nc,1.997091e+13,0.720,-20.768,A,845,AO,20181011180521
...,...,...,...,...,...,...,...,...
2984596,nmdis/2901633/profiles/R2901633_067.nc,2.013050e+13,27.462,139.107,P,841,NM,20130507103443
2984597,nmdis/2901633/profiles/R2901633_068.nc,2.013051e+13,27.432,138.840,P,841,NM,20130511165723
2984598,nmdis/2901633/profiles/R2901633_069.nc,2.013052e+13,27.692,138.677,P,841,NM,20130521170139
2984599,nmdis/2901633/profiles/R2901633_070.nc,2.013053e+13,27.895,138.465,P,841,NM,20130531181516
2984600,nmdis/2901633/profiles/R2901633_071.nc,2.013061e+13,27.931,138.090,P,841,NM,20130617181801

In [3]:
polygon = pd.read_csv("data/off_bcs.csv", usecols=['latitude','longitude'])
polygon

   latitude  longitude
0        25       -113
1        25       -105
2        17       -105
3        17       -113
4        25       -113

In [4]:
df, fig = cluster_qc.get_profiles_within_polygon(directory, polygon, storage_path="./data", plot=False)
df["file_path"] = ("C:/bd/argo/202406-ArgoData/dac/" + df["file"]) # Configure file paths
df

,file,date,latitude,longitude,ocean,profiler_type,institution,date_update,file_path
0,aoml/1902645/profiles/R1902645_001.nc,2.024052e+13,20.897,-111.494,P,846,AO,20240531190116,C:/bd/argo/202406-ArgoData/dac/aoml/1902645/pr...
1,aoml/1902645/profiles/R1902645_002.nc,2.024053e+13,20.816,-111.461,P,846,AO,20240531190117,C:/bd/argo/202406-ArgoData/dac/aoml/1902645/pr...
2,aoml/1902645/profiles/R1902645_003.nc,2.024053e+13,20.731,-111.402,P,846,AO,20240531190117,C:/bd/argo/202406-ArgoData/dac/aoml/1902645/pr...
3,aoml/1902645/profiles/R1902645_004.nc,2.024053e+13,20.645,-111.341,P,846,AO,20240601070103,C:/bd/argo/202406-ArgoData/dac/aoml/1902645/pr...
4,aoml/1902645/profiles/R1902645_005.nc,2.024060e+13,20.567,-111.276,P,846,AO,20240603110041,C:/bd/argo/202406-ArgoData/dac/aoml/1902645/pr...
...,...,...,...,...,...,...,...,...,...
3141,meds/4902475/profiles/R4902475_180.nc,2.024042e+13,22.282,-111.119,P,844,ME,20240422191552,C:/bd/argo/202406-ArgoData/dac/meds/4902475/pr...
3142,meds/4902475/profiles/R4902475_181.nc,2.024050e+13,22.723,-111.236,P,844,ME,20240503011550,C:/bd/argo/202406-ArgoData/dac/meds/4902475/pr...
3143,meds/4902475/profiles/R4902475_182.nc,2.024051e+13,22.969,-111.542,P,844,ME,20240513131558,C:/bd/argo/202406-ArgoData/dac/meds/4902475/pr...
3144,meds/4902475/profiles/R4902475_183.nc,2.024052e+13,23.240,-111.777,P,844,ME,20240523101549,C:/bd/argo/202406-ArgoData/dac/meds/4902475/pr...
3145,meds/4902475/profiles/R4902475_184.nc,2.024060e+13,22.955,-111.833,P,844,ME,20240602161551,C:/bd/argo/202406-ArgoData/dac/meds/4902475/pr...

In [5]:
data = cluster_qc.get_data_from_source(files=df.file_path.values)
data.to_csv("./data/profile_measurements.csv", index=False)
data

C:\Users\USER\anaconda3\lib\site-packages\xarray\backends\plugins.py:80: RuntimeWarning: Engine 'gini' loading failed:]
No module named 'pooch'
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)
Reading profiles: 100%|██████████████████████████████████████████████████████████| 3146/3146 [01:02<00:00, 50.10file/s]

,PLATFORM_NUMBER,CYCLE_NUMBER,DATA_MODE,DATE,LATITUDE,LONGITUDE,PRES,TEMP,PSAL
0,1902645,1,A,2024-05-23 07:01:06.000752640,20.897200,-111.494100,4.310000,22.389999,34.577000
1,1902645,1,A,2024-05-23 07:01:06.000752640,20.897200,-111.494100,6.110000,22.388000,34.577000
2,1902645,1,A,2024-05-23 07:01:06.000752640,20.897200,-111.494100,8.110000,22.381001,34.576000
3,1902645,1,A,2024-05-23 07:01:06.000752640,20.897200,-111.494100,10.110000,22.375000,34.576000
4,1902645,1,A,2024-05-23 07:01:06.000752640,20.897200,-111.494100,12.110000,22.385000,34.576000
...,...,...,...,...,...,...,...,...,...
1817306,4902475,184,R,2024-06-02 17:38:00.000000000,22.954834,-111.832855,1985.400024,2.277000,34.632000
1817307,4902475,184,R,2024-06-02 17:38:00.000000000,22.954834,-111.832855,1995.400024,2.261000,34.632999
1817308,4902475,184,R,2024-06-02 17:38:00.000000000,22.954834,-111.832855,2005.500000,2.245000,34.632999
1817309,4902475,184,R,2024-06-02 17:38:00.000000000,22.954834,-111.832855,2016.099976,2.226000,34.633999
1817310,4902475,184,R,2024-06-02 17:38:00.000000000,22.954834,-111.832855,2021.000000,2.217000,34.634998